# Generated by Django 5.2.11 on 2026-02-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={
                "ordering": ["building", "apartment_no"],
                "verbose_name": "شقة",
                "verbose_name_plural": "الشقق",
            },
        ),
        migrations.AlterModelOptions(
            name="building",
            options={
                "ordering": ["name"],
                "verbose_name": "عمارة",
                "verbose_name_plural": "العمارات",
            },
        ),
        migrations.AlterModelOptions(
            name="lease",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "عقد",
                "verbose_name_plural": "العقود",
            },
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["full_name"],
                "verbose_name": "مستأجر",
                "verbose_name_plural": "المستأجرون",
            },
        ),
        migrations.AlterField(
            model_name="apartment",
            name="apartment_no",
            field=models.CharField(max_length=50, verbose_name="رقم الشقة"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="area_m2",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="المساحة (م²)"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="listings.building",
                verbose_name="العمارة",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="floor",
            field=models.CharField(blank=True, max_length=50, verbose_name="الطابق"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rent_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="قيمة الإيجار"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rooms",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="عدد الغرف"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="status",
            field=models.CharField(
                choices=[("VACANT", "شاغرة"), ("RENTED", "مؤجرة"), ("MAINT", "صيانة")],
                default="VACANT",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=150, verbose_name="اسم العمارة"),
        ),
        migrations.AlterField(
            model_name="building",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="listings.apartment",
                verbose_name="الشقة",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ النهاية"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="rent_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="قيمة الإيجار المتفق عليها",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="security_deposit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="مبلغ التأمين"
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="start_date",
            field=models.DateField(verbose_name="تاريخ البداية"),
        ),
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "نشط"), ("ENDED", "منتهي")],
                default="ACTIVE",
                max_length=10,
                verbose_name="حالة العقد",
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="listings.tenant",
                verbose_name="المستأجر",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="اسم المستأجر"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم الهوية"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم الهاتف"
            ),
        ),
    ]
