# Generated by Django 5.2.11 on 2026-02-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_apartment_options_alter_building_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(verbose_name="نص العقد")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "قالب عقد",
                "verbose_name_plural": "قوالب العقود",
                "ordering": ["-is_active", "title"],
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="id_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tenant_ids/",
                verbose_name="صورة الهوية",
            ),
        ),
    ]
