# Generated by Django 5.2.11 on 2026-02-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_contracttemplate_tenant_id_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="العنوان"),
        ),
    ]
