# Generated by Django 5.2.11 on 2026-02-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_tenant_address"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("apartment",),
                name="unique_active_lease_per_apartment",
            ),
        ),
    ]
