# Generated by Django 5.2.11 on 2026-02-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_lease_unique_active_lease_per_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tenant_photos/",
                verbose_name="الصورة الشخصية",
            ),
        ),
    ]
