# Generated by Django 5.2.11 on 2026-02-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_tenant_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "نشط"), ("EXPIRED", "منتهي"), ("ENDED", "منتهي")],
                default="ACTIVE",
                max_length=10,
                verbose_name="حالة العقد",
            ),
        ),
    ]
